<a href="https://colab.research.google.com/github/Padmini-c4/DataScience_Task/blob/main/Numpy_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Part 1: Creating and Reshaping Arrays

In [ ]:
#import necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# 1. Create Arrays
# o Create two NumPy arrays:
# ▪ A 1D array of 10 equally spaced values between 0 and 50.
# ▪ A 2D array of shape (3x3) containing random integers between 5 and 20.
arr=np.linspace(0,50,10)
arr1=np.random.randint(5,21,9)
print(arr1)
arr2=arr1.reshape(3,3)
print(arr2)

[16 20 19 19 15 17 10 13 16]
[[16 20 19]
 [19 15 17]
 [10 13 16]]


In [ ]:
# 2. Array Dimensions:
# o Print the dimensions of both arrays.
# o Print the shape of both arrays.
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)

1
2
(9,)
(3, 3)


In [ ]:
# 3. Reshaping:
# o Reshape the 1D array into a 2D array with shape (2x5).
# o Print the reshaped array.
# o Flatten the reshaped array back to 1D and print it.
arr3=arr.reshape(2,5)
print(arr3)
arr3=arr.reshape(-1)
print(arr3)

[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


#Part 2: Indexing and Slicing

In [ ]:
# 4. Indexing:
# o For the 2D array created in Part 1, print the element present at the 2nd row and 3rd column.
# o Extract the first two rows and the last two columns of the array.
print(arr2[1][2])
print(arr2[1])

17
[19 15 17]


In [ ]:
# 5. Slicing:
# o Slice the first four elements from the flattened 1D array.
# o Reverse the elements of the 1D array using slicing.
print(arr2[0:2,1:])
print(arr2[:4])
print(arr2[::-1])


[[20 19]
 [15 17]]
[[16 20 19]
 [19 15 17]
 [10 13 16]]
[[10 13 16]
 [19 15 17]
 [16 20 19]]


#Part 3: Array Operations

In [ ]:
# 6. Array Arithmetic:
# o Create another 1D array of 10 integers between 1 and 10.
# o Perform the following element-wise operations between the 1D arrays created in Part 1 and Part 3:
# ▪ Addition
# ▪ Multiplication
# ▪ Subtract a constant value (e.g., 5) from the array.
arr4=np.arange(1,11)
print(arr4)
print(arr4+arr4)
print(arr4*arr4)
print(arr4-3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]
[-2 -1  0  1  2  3  4  5  6  7]


#Part 4: Random Number Generation and Copying

In [ ]:
# 7. Random Numbers:
# o Create a 1D array of 5 random values between 0 and 1.
# o Create another 1D array of 5 random values between -1 and 1.
arr5=np.random.rand(5)
print(arr5)
arr6=np.random.randn(1,5)
print(arr6)

[0.18100149 0.49017444 0.2105028  0.13558813 0.59059503]
[[-0.69550089 -0.35021632 -0.21020677 -1.61572433  0.22404897]]


#Part 5: Bonus

In [ ]:
# 8. Challenge Task:
# o Write a program that asks the user to input a number (n), and then generates an n x n array of random integers between 1 and 100.
# o Find the sum of all the elements in the array and print the result.
n=int(input())
arr1=np.random.randint(1,100,n*n)
print(arr1.reshape(n,n))
np.sum(arr1)

4
[[92  5 26 73]
 [44 71 86 50]
 [15 32 60 97]
 [39 55 43 74]]


np.int64(862)